Backend fix djoser urls
international-team-management/team-platform pull request #200
Opened 2023-08-28 19:15 UTC by MorozovP

Удалил неиспользуемые эндпоинты и методы.

2023-08-29 08:06 UTC, desm80 requested changes

2023-08-29 08:06 UTC, desm80 commented on backend/itm_backend/api/views.py
> +from users.models import User
мне кажется что хорошая практика не импортировать Юзера напрямую, а User = get_user_model()

2023-08-30 07:05 UTC, desm80 approved these changes

2023-08-30 09:22 UTC, Leenominai approved these changes

2023-09-01 05:38 UTC, merged