pytest
international-team-management/team-platform pull request #203
Opened 2023-08-30 05:02 UTC by lazarenkov-e

Ребята, я извиняюсь, что долго ковырял эти тесты. Для меня какая-то бесконечная история. 
Уверен, что можно будет добавить еще каких-то проверок, но решил выложить, что есть. Времени тянуть это уже нет, как-будто. Нам нужно с Сашей их будет запустить на серваке после мерджа, насколько я помню.

2023-08-31 11:59 UTC, desm80 requested changes

2023-08-31 11:59 UTC, desm80 commented on backend/itm_backend/users/migrations/0001_initial.py
> +# Generated by Django 3.2.20 on 2023-08-30 04:16
Не нужно миграции закидывать в ПР, от них только конфликты бесконечные, потом Саша на сервере создаст все с нуля. Будем надеяться, что этонормальный подход.

2023-08-31 11:59 UTC, desm80 commented on backend/tests/test_projects.py
> +            f"`{self.project_list_url}` возвращает список всех постов."
У меня только такие вот замечания пока есть, они не по существу, больше по оформлению....Вместо пост нужно проект....там дальше еще есть такие ляпы

2023-09-02 06:01 UTC, lazarenkov-e commented on backend/itm_backend/users/migrations/0001_initial.py
> +# Generated by Django 3.2.20 on 2023-08-30 04:16
О! я только за то, чтобы их убрать. Эта сборка была наследована от бэкэнда 30.08.23 и там они были, поэтому и я закинул. Вы добавили их в гитигнор?

2023-09-02 06:08 UTC, lazarenkov-e commented on backend/tests/test_projects.py
> +            f"`{self.project_list_url}` возвращает список всех постов."
Ок. За образец брал наши учебные проекты. Не заметил, как посты пролезли...

2023-09-02 06:10 UTC, lazarenkov-e commented
Внес правки после ревью Дениса

2023-09-02 06:50 UTC, desm80 approved these changes

2023-09-02 09:18 UTC, Leenominai approved these changes

2023-09-02 13:56 UTC, closed without merging