Backend feat swagger edit
international-team-management/team-platform pull request #204
Opened 2023-08-30 07:28 UTC by Leenominai

Привёл сваггер к красивому виду.
Проверьте вид и функционал на своих машинах.
Если надо будет, то я потом какие-то файлики уберу из PR.

2023-08-30 09:16 UTC, MorozovP commented on backend/itm_backend/api/serializers.py
> +
Тут нужно будет привести к виду 
{
  "new_password": "string",
  "current_password": "string"
}
Я в своем ПР исправлю

2023-08-30 09:19 UTC, Leenominai commented on backend/itm_backend/api/serializers.py
> +
> Тут нужно будет привести к виду { "new_password": "string", "current_password": "string" } Я в своем ПР исправлю

Да, я в итоге брал за основу твой новый сериализатор. А в самом swagger'е я сделал в итоге так, что у меня запрашивает только одно поле - new_password без current_password - и это работает (при наличии авторизации через токен).

![image](https://github.com/international-team-management/team-platform/assets/40167164/c05fd819-dfdc-46e1-b1a8-1d67c58f82ec)

В итоге там только одно поле:

![image](https://github.com/international-team-management/team-platform/assets/40167164/19611515-8c0f-42ca-a7eb-99a4c88a2e4a)

2023-08-30 09:23 UTC, MorozovP commented on backend/itm_backend/api/serializers.py
> +
Запускал эту версию вместе с фронтом? Мне кажется не должно работать.

2023-08-30 09:24 UTC, Leenominai commented on backend/itm_backend/api/serializers.py
> +
> Запускал эту версию вместе с фронтом? Мне кажется не должно работать.

Нет ещё, только бэк тестил по ветке backend.

2023-08-30 10:34 UTC, desm80 approved these changes

2023-08-31 17:33 UTC, MorozovP requested changes

2023-08-31 17:33 UTC, MorozovP commented on backend/itm_backend/api/views.py
> +    create=extend_schema(
Предлагаю extend_schema_view вынести в отдельный файл

2023-09-01 16:57 UTC, closed without merging