Fixed mistakes from flake8 in pre-commit
international-team-management/team-platform pull request #231
Opened 2023-09-06 12:11 UTC by lazarenkov-e

Исправил. Добавил def get_queryset(self): во вьюху для Тасков.
Также удалил несолько неиспользуемых переменных, на которые ругался flake8 во время пре-коммита:
На всякий случай их обозначу:
backend/itm_backend/api/views.py:12:1: F401 'api.services.PROJECT_EXAMPLE_NAME' imported but unused
backend/itm_backend/api/views.py:12:1: F401 'api.services.add_project_example' imported but unused
backend/itm_backend/api/views.py:22:1: F401 '.decorators.project_view_project_example' imported but unused
Я их потер!

2023-09-06 13:19 UTC, desm80 commented on backend/itm_backend/api/views.py
> +        task_project_id = self.kwargs["projects_id"]
Метод get() позволяет вернуть значение словаря по ключу, если оно существует, или другое, если указано (по-умолчанию возвращает None). Метод get() не вызывает исключение (ошибка KeyError), если ключ не существует, в отличии от прямого запроса к несуществующему ключу в словаре.

Лучше сделать self.kwargs.get("projects_id")

2023-09-06 13:27 UTC, desm80 requested changes

2023-09-06 13:27 UTC, desm80 commented on backend/itm_backend/api/views.py
>      queryset = Task.objects.all()
насколько я помню, не нужно указывать queryset = Task.objects.all() если мы переопределяем метод def get_queryset(self):

2023-09-06 21:02 UTC, lazarenkov-e commented on backend/itm_backend/api/views.py
>      queryset = Task.objects.all()
протупил пол часа, так и не понял почему, но без этой строчки не работает. Более того, если ее запихать например в def get_queryset(self):
    queryset = Task.objects.all()
    task_project_id = self.kwargs.get("projects_id")
    if task_project_id is not None:
        queryset = Task.objects.filter(task_project=task_project_id)
    return queryset

Тоже не работает!((( на сегодня я сдаюсь)

2023-09-06 21:05 UTC, lazarenkov-e commented
метод get добавил. строчку не убрал

2023-09-07 05:11 UTC, desm80 commented on backend/itm_backend/api/views.py
>      queryset = Task.objects.all()
При работе с вьюсетами и роутерами вы можете столкнуться с ошибкой «не определён аргумент basename»:
'basename' argument not specified, and could not automatically determine the name from the viewset, as it does not have a '.queryset' attribute. 
Речь идёт о необязательном аргументе роутера basename: в нём можно вручную указать префикс для параметра name в эндпоинтах, созданных роутером. 
Например, можно переопределить префикс cat в name='cat-list' и name='cat-detail'
router.register('cats', CatViewSet, basename='tiger') 
В результате name для эндпоинтов будут начинаться с tiger:
urlpatterns = [
    path('cat/', ..., name='tiger-list'),
    path('cat/<int:pk>/', ..., name='tiger-detail'),
] 
Однако есть случаи, когда параметр basename обязательно должен быть указан. Это необходимо в тех случаях, когда queryset однозначно не задан во вьюсете, а определён через метод get_queryset().
# Если бы пользователи могли оставлять комментарии к котикам, 
# то эндпоинт для работы с комментариями выглядел бы примерно так:
# cats/{cat_id}/comments/

class CommentViewSet(viewsets.ModelViewSet):
    serializer_class = CommentSerializer
    # queryset во вьюсете не указываем
    # Нам тут нужны не все комментарии, а только связанные с котом с id=cat_id
    # Поэтому нужно переопределить метод get_queryset и применить фильтр
    def get_queryset(self):
        # Получаем id котика из эндпоинта
        cat_id = self.kwargs.get("cat_id")
        # И отбираем только нужные комментарии
        new_queryset = Comment.objects.filter(cat=cat_id)
        return new_queryset 
В подобных ситуациях создать name автоматически не получится, и параметр basename придётся указать явным образом.

2023-09-07 05:14 UTC, desm80 commented on backend/itm_backend/api/views.py
>      queryset = Task.objects.all()
Выдержка из теории ЯндексПрактикум))))  тебе нужно было явным образом указать basename в router)

Спринт 8/25 → Тема 1/3: Django Rest Framework → Урок 8/15

2023-09-07 09:01 UTC, lazarenkov-e commented on backend/itm_backend/api/views.py
>      queryset = Task.objects.all()
Спасибо за наводку!)) исправил

2023-09-07 10:43 UTC, desm80 approved these changes

2023-09-07 10:44 UTC, merged