Backend
international-team-management/team-platform pull request #36
Opened 2023-07-24 12:19 UTC by desm80

merge для отправки на первое ревью.
На данный момент завершены подготовительные мероприятия:
- Создана среда разработки на основе poetry 1.5.1;
- Выбран стек для приложения: pytho3.9, Django3.2, drf3.14, djoser2.2, djangorestframework-simplejwt, psycopg2-binary, gunicorn, drf-spectacular, pre-commit, black;
- Все выбранные зависимости установлены и интегрированы в проект;
- Описан Dockerfile для сборки контейнера приложения;
- Описан docker-compose.yml для локального развертывания проекта совместно с базой данных postgres;
- Установлен автоматический генератор документации АПИ в форматах Redoc, Swagger.  После запуска контейнеров доступны по адресам localhost:8000/api/v1/swagger-ui/,  localhost:8000/api/v1/redoc/
В приложении запущены 3 приложения: api, users. projects.
В приложении users завершены первоначальный настройки модели User и кастомизация базовых сериализаторов.

2023-08-03 02:16 UTC, ReznikovRoman requested changes
Хорошее начало! Есть еще несколько предложений по доработкам

2023-08-03 02:16 UTC, ReznikovRoman commented on .github/workflows/git-workflow.yml
> +
Еще стоит добавить джобу по сборке образа бэкенда и отправке в image regitry (для всего этого уже есть готовый github action)

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/api/admin.py
> +from django.contrib import admin
Все файлы, которые не связаны с АПИ из этого приложения/пустые файлы (кроме __init__, конечно) нужно удалить

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/itm_backend/asgi.py
> +"""
Комментарии, которые генерируются самим Джанго, можно спокойно удалять - они только место занимают

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/itm_backend/settings.py
> +    "api.apps.ApiConfig",
Порядок приложений в `INSTALLED_APPS` имеет большое значение, поэтому лучше располагать подключенные приложения примерно таким образом: приложения от Джанго, приложения от сторонних библиотек (некоторые библиотеки нужно подключать раньше стандартных приложений Джанго, но это будет описано в документации), свои собственные приложения

То есть в этом случае просто надо опустить ваши приложения ниже

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/itm_backend/settings.py
> +# DATABASES = {
Весь закоментированный код надо удалять

2023-08-03 02:16 UTC, ReznikovRoman commented on infra/docker-compose.yml
> +  backend:
Запуск миграций и сборку статики нужно делать при запуске контейнера здесь в докер композе (либо можно добавить скрипт с необходимыми командами в `ENTRYPOINT` в докерфайле)

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/users/serializers.py
> +from django.contrib.auth import get_user_model
Все, что связано с АПИ (сериалайзеры, вьюхи, урлы и т.п.) должно находиться в соответствующей папке `api`

Из Джанго приложения это нужно убрать

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/users/serializers.py
> +        fields = "__all__"
Использование `__all__` в формах/сериалайзерах/фильтрах обычно считается антипаттерном (с `exclude` аналогично) - стоит вручную прописывать все поля, которые ты хочешь использовать

Проблема с `__all__` в том, что если в модель добавится какое-то поле, которое не нужно/нельзя из соображений безопасности отдавать по АПИ, то придется еще обязательно проверить все подобные сериализаторы и исключить это поле (но скорее всего, разработчики просто забудут это сделать -> баг/утечка лишних данных)

Проверьте это во всем проекте

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/users/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="timetables")
Для полей моделей лучше задавать [`verbose_name`](https://docs.djangoproject.com/en/4.1/ref/models/fields/#verbose-name) - "человекочитаемое" описание поля в БД (оно будет отображаться в админке)

Проверьте во всех моделях

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/users/models.py
> +    ROLE_CHOICES = (("admin", "Администратор"), ("editor", "Редактор"), ("executor", "Исполнитель"))
Для подобного перечисления лучше использовать либо питоновский `enum.Enum`, либо `models.TextChoices` из [Джанго](https://docs.djangoproject.com/en/4.1/ref/models/fields/#enumeration-types)

2023-08-03 02:16 UTC, ReznikovRoman commented on backend/itm_backend/users/models.py
> +    def save(self, *args, **kwargs):
У Джанго есть заданный "Coding style", [по моделям можно почитать тут](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style) (для сериалайзеров тоже можно придерживаться таких правил)

Чтобы постоянно не думать об этих правилах, советую установить плагин к flake8 - [`flake8-django`](https://github.com/rocioar/flake8-django)

2023-08-03 02:16 UTC, ReznikovRoman commented on .github/workflows/git-workflow.yml
> +  send_message:
Это какая-то лишняя джоба :) Вы же в любом случае увидите сообщение об успешно завершенном пайплайнеэ

Скорее всего, вы хотели тут добавить отправку сообщения в телеграм (это необязательно, но имело бы хоть какой-то смысл)

2023-08-11 07:05 UTC, MorozovP approved these changes

2023-08-17 11:28 UTC, MorozovP commented on .github/workflows/git-workflow.yml
> +
Замечание исправили, но пока убрали запуск воркфлоу при пуше в эту ветку. Добавим позже.

2023-08-17 11:28 UTC, MorozovP commented on backend/itm_backend/api/admin.py
> +from django.contrib import admin
Исправлено

2023-08-17 11:28 UTC, MorozovP commented on backend/itm_backend/itm_backend/asgi.py
> +"""
Исправлено

2023-08-17 11:29 UTC, MorozovP commented on backend/itm_backend/itm_backend/settings.py
> +    "api.apps.ApiConfig",
Исправлено

2023-08-17 11:29 UTC, MorozovP commented on backend/itm_backend/itm_backend/settings.py
> +# DATABASES = {
Исправлено

2023-08-17 11:42 UTC, MorozovP commented on infra/docker-compose.yml
> +  backend:
Исправлено

2023-08-17 11:42 UTC, MorozovP commented on backend/itm_backend/users/serializers.py
> +        fields = "__all__"
Исправлено

2023-08-17 11:42 UTC, MorozovP commented on backend/itm_backend/users/serializers.py
> +from django.contrib.auth import get_user_model
Исправлено

2023-08-17 11:43 UTC, MorozovP commented on backend/itm_backend/users/models.py
> +    def save(self, *args, **kwargs):
Установили flake8-django

2023-08-17 11:43 UTC, MorozovP commented on backend/itm_backend/users/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="timetables")
Добавили

2023-08-18 12:20 UTC, merged