added task model
international-team-management/team-platform pull request #66
Opened 2023-08-03 18:16 UTC by Picnichek

Добавил модель и сериализаторы. Не совсем понимаю, что нужно в сериализаторе указать. Поэтому сделал стандартные (указал все). Гляньте, что не так :)

2023-08-04 06:55 UTC, desm80 requested changes

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/projects/admin.py
> +        if db_field.name == "owner":
Вместо "owner" нужно поставить "creator" у Таска нет поля owner

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/projects/models.py
> +        related_name="created_tasks",
мы вроде решили, что Юзеров не удаляем, я ставил PROTECT

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/projects/models.py
> +    tags = models.ManyToManyField(Tag, related_name="related_tasks", verbose_name="Тэги")
Тэгов может и не быть, их могут добавить уже после создания Таски....

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/projects/models.py
> +    deadline = models.DateTimeField(verbose_name="Срок исполнения задачи")
Мне показалось в качестве дедлайна достаточно только Даты, врядли будет критично ровно в полдень 4 августа ставить дедлайн)

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/projects/models.py
> +        production = "Production", _("Проект взлетел")
Задача взлетела?))))

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/projects/models.py
> +        verbose_name="Статус проекта",
Статус задачи

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/users/models.py
> +    role = models.CharField(
Тимур предлагает сделать это поле без выбора, просто CharField

2023-08-04 06:55 UTC, desm80 commented on backend/itm_backend/users/models.py
telephone_number = models.SmallIntegerField(verbose_name="Номер телефона", blank=True, null=True)

Тимур опять же указал, что телефон в SmallIntegerField не влезает...куча споров как сделать правильно...если следовать https://ru.wikipedia.org/wiki/E.164 то это должны быть цифры (int), но если у нас будут приходить  + и () то наверное varchar

2023-08-04 08:11 UTC, Leenominai commented on backend/itm_backend/projects/models.py
> +    deadline = models.DateTimeField(verbose_name="Срок исполнения задачи")
"обносления" обновления*

2023-08-04 11:37 UTC, Leenominai commented on backend/itm_backend/projects/models.py
>      deadline = models.DateField(verbose_name="Дата окончания проекта")
Судя по дизайну в Figma у проекта должно быть ещё и начало, как вариант - автовыбор времени создания самого проекта.

2023-08-04 11:37 UTC, Leenominai commented on backend/itm_backend/projects/models.py
>      deadline = models.DateField(verbose_name="Дата окончания проекта")
![image](https://github.com/international-team-management/team-platform/assets/40167164/ae97889d-3dac-42c1-a2bb-a15c8f0eb227)

2023-08-04 11:37 UTC, Leenominai commented on backend/itm_backend/projects/models.py
> +                TaskUser.objects.get_or_create(user_id=user, task_id=self)
Мне вот что предложил чат по методу сохранения:
```
from django.core.exceptions import ObjectDoesNotExist
...

try:
    TaskUser.objects.get(user_id=user, task_id=self)
except ObjectDoesNotExist:
    TaskUser.objects.create(user_id=user, task_id=self)
```
И вот какое объяснение:
Метод save переопределен для модели Task. При сохранении объекта Task (то есть при вызове task_instance.save()), этот метод будет выполняться.

self.id - это проверка, есть ли у текущего объекта Task уже присвоен идентификатор (то есть, сохранен ли объект в базе данных). Если self.id равен None, значит объект еще не сохранен в базе.

self.assigned_to.exists() - это проверка, есть ли у объекта Task связанные исполнители (assigned_to). Мы используем .exists() для проверки, так как self.assigned_to - это связанный менеджер (related manager), который может быть пустым (не содержать исполнителей), и мы хотим убедиться, что у нас есть хотя бы один связанный исполнитель.

Если оба условия выполняются (есть id и есть хотя бы один связанный исполнитель), то мы переходим к следующему шагу.

В этом шаге мы итерируем по всем связанным исполнителям (assigned_to) текущей задачи.

Для каждого исполнителя проверяем существует ли уже связь с этим исполнителем и текущей задачей в модели TaskUser. Для этого используем метод .get() и передаем ему условия поиска (user_id=user и task_id=self). Если объект TaskUser с такими условиями не найден, возникает исключение ObjectDoesNotExist.

Если в результате поиска объект TaskUser не найден (возникло исключение ObjectDoesNotExist), это означает, что для этого исполнителя еще нет связи с текущей задачей. В таком случае, мы создаем новый объект TaskUser с помощью метода create и связываем его с текущим исполнителем и задачей.

Таким образом, данный код гарантирует, что каждому исполнителю будет соответствовать только один объект TaskUser для каждой задачи. Это предотвращает возникновение дубликатов и обеспечивает корректную связь между исполнителями и задачами.

2023-08-04 11:40 UTC, Leenominai commented on backend/itm_backend/users/models.py
> +    telephone_number = models.CharField(verbose_name="Номер телефона", blank=True, null=True, max_length=20)
Смотрю в интернете - есть спец библиотека [django-phonenumber-field](https://pypi.org/project/django-phonenumber-field/ со своим PhoneNumberField, можно попробовать её использовать (я не пробовал).
Вот пример, как я нашёл её:
https://stackoverflow.com/questions/19130942/whats-the-best-way-to-store-a-phone-number-in-django-models

2023-08-04 11:47 UTC, MorozovP commented on backend/itm_backend/projects/models.py
> +                TaskUser.objects.get_or_create(user_id=user, task_id=self)
Не совсем понятно, код, который чат предлагает это только замена  get_or_create
https://docs.djangoproject.com/en/4.2/ref/models/querysets/#get-or-create

А объяснение, кажется, относится именно к коду Кирилла..

2023-08-04 12:00 UTC, Leenominai commented on backend/itm_backend/projects/models.py
> +                TaskUser.objects.get_or_create(user_id=user, task_id=self)
Да я сам ещё посмотрел и думаю, по сути, не должно быть разницы для нас.
Поэтому в целом можно оставить и так как было.

2023-08-04 17:40 UTC, Leenominai commented on backend/itm_backend/projects/serializers.py
> +        fields = "__all__"
Наш ревьюер оставил комментарией по поводу сериализаторов:

"""
Использование __all__ в формах/сериалайзерах/фильтрах обычно считается антипаттерном (с exclude аналогично) - стоит вручную прописывать все поля, которые ты хочешь использовать

Проблема с __all__ в том, что если в модель добавится какое-то поле, которое не нужно/нельзя из соображений безопасности отдавать по АПИ, то придется еще обязательно проверить все подобные сериализаторы и исключить это поле (но скорее всего, разработчики просто забудут это сделать -> баг/утечка лишних данных)

Проверьте это во всем проекте
"""
Можно вместе обсудить, стоит это сразу исправлять или позже сделаем.

2023-08-04 17:40 UTC, Leenominai commented on backend/itm_backend/projects/serializers.py
> +        fields = "__all__"
Вот скрин:

![image](https://github.com/international-team-management/team-platform/assets/40167164/390b8a0a-b4aa-4e63-ba09-10ee192f1914)

2023-08-05 07:35 UTC, MorozovP approved these changes

2023-08-05 07:39 UTC, MorozovP approved these changes

2023-08-05 07:50 UTC, MorozovP approved these changes

2023-08-05 08:01 UTC, merged